/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
let mongoose = require('mongoose');
let config = require('config');
let Schema = mongoose.Schema;
autoIncrement = require('mongoose-plugin-autoinc');
mongoose.Promise = global.Promise;
let mongoosePaginate = require('mongoose-paginate');
let connection = mongoose.createConnection(config.db.connection + ':27017/' + config.db.name);
let posp_user_loginSchema = new Schema({
    'User_Id': Number,
    'Mobile_Number': String,
    'Onboarding_Status': {type: String,
        enum: ["InProcess", "OTP_Verified", "Sign_Up", "Training_Scheduled", "Doc_Uploaded","Doc_Rejected", "Doc_Verified", "Doc_Approved", "IIB_Checked", "Exam_Started", "Exam_Completed", "Erp_Id_Created"],
        default: "InProcess"
    },
    'Training_Start_Date': {type: Date, default: ""},
    'Training_End_Date': {type: Date, default: ""},
    'Completed_Hours': {type: String, default: ""},
    'Remaining_Hours': {type: String, default: ""},
    'Training_Status': {type: String, default: ""},
    'Exam_Status': {type: String, default: ""},
    "Exam_Start_Date": {type: Date, default: ""},
    "Exam_End_Date": {type: Date, default: ""},
    'Payment_Status': {type: String, default: ""},
    'Package_Id': {type: Number, default: 0},
    'PayId': {type: String, default: ""},
    "Package_Amount": {type: Number, default: 0},
    'Is_Training_Completed': {type: String, default: "No"},
    'Is_Document_Uploaded': {type: String, default: "No"},
    'Is_Document_Rejected': {type: String, default: "No"},
    'Is_IIB_Uploaded': {type: String, default: "No"},
    'IIB_Uploaded_On': {type: Date},
    'IIB_Uploaded_Ack': {type: String, default: "No"},
    'Is_Doc_Verified': {type: String, default: "No"},
    'Is_Appointment_Letter_Generated': {type: String, default: "No"},
    'Is_Certificate_Generated': {type: String, default: "No"},
    'Is_Invoice_Generated': {type: String, default: "No"},
    'Is_Doc_Approved': {type: String, default: "No"},
    'Last_Module_Id': {type: Number, default: 3},
    'Last_Module_Name': {type: String, default: "General Insurance"},
    'Last_Chapter': {type: Number, default: 1},
    'Last_Page': {type: Number, default: 1},
    'POSP_UploadingDateAtIIB': {type: String, default: ""},
    'Posp_Id': Number,
    'Fba_Id': Number,
    'Sm_Posp_Id': Number,
    'Sm_Posp_Name': {type: String, default: ""},
    'First_Name': {type: String, default: ""},
    'Middle_Name': {type: String, default: ""},
    'Last_Name': {type: String, default: ""},
    'Father_Name': {type: String, default: ""},
    'Email_Id': {type: String, default: ""},
    'Agent_City': {type: String, default: ""},
    'Telephone_No': {type: String, default: ""},
    'Mobile_No': {type: String, default: ""},
    'Education': {type: String, default: ""},
    'Birthdate': {type: String, default: ""},
    'Permanant_Add1': {type: String, default: ""},
    'Permanant_Add2': {type: String, default: ""},
    'Permanant_Add3': {type: String, default: ""},
    'Permanant_Landmark': {type: String, default: ""},
    'Permanant_Pincode': Number,
    'Permanant_City': {type: String, default: ""},
    'Permanant_State': {type: String, default: ""},
    'Present_Add1': {type: String, default: ""},
    'Present_Add2': {type: String, default: ""},
    'Present_Add3': {type: String, default: ""},
    'Present_Landmark': {type: String, default: ""},
    'Present_Pincode': Number,
    'Present_City': {type: String, default: ""},
    'Present_State': {type: String, default: ""},
    'Pan_No': {type: String, default: ""},
    'Aadhar': {type: String, default: ""},
    'Experience': Number,
    'Income': Number,
    'Already_Posp': {type: String, default: "No"},
    'Legal_case': {type: String, default: ""},
    'Bank_Account_No': {type: String, default: ""},
    'Account_Type': {type: String, default: ""},
    'Ifsc_Code': {type: String, default: ""},
    'Micr_Code': {type: String, default: ""},
    'Bank_Name': {type: String, default: ""},
    'Bank_Branch': {type: String, default: ""},
    'Sources': {type: String, default: ""},
    'Last_Status': {type: String, default: ""},
    'Status_Remark': {type: String, default: ""},
    'Document_Name': {type: String, default: ""},
    'Document_Type': {type: String, default: ""},
    'Service_Tax_Number': {type: String, default: ""},
    'Nominee_Aadhar': {type: String, default: ""},
    'Nominee_Account_Type': {type: String, default: ""},
    'Nominee_Bank_Account_Number': {type: String, default: ""},
    'Nominee_Bank_Branch': {type: String, default: ""},
    'Nominee_Bank_City': {type: String, default: ""},
    'Nominee_Bank_Name': {type: String, default: ""},
    'Nominee_First_Name': {type: String, default: ""},
    'Nominee_Middle_Name': {type: String, default: ""},
    'Nominee_Last_Name': {type: String, default: ""},
    'Nominee_Micr_Code': {type: String, default: ""},
    'Nominee_Ifsc_Code': {type: String, default: ""},
    'Nominee_Name_as_in_Bank': {type: String, default: ""},
    'Is_Active': {type: Boolean, default: false},
    'Ss_Id': Number,
    'Erp_Id': {type: String, default: ""},
    'Erp_Msg': {type: String, default: ""},
    'Erp_Status': {type: String, default: ""},
    'Gender': {type: String, default: ""},
    'Name_as_in_Bank': {type: String, default: ""},
    'Nominee_Gender': {type: String, default: ""},
    'Nominee_Relationship': {type: String, default: ""},
    'Nominee_Pan': {type: String, default: ""},
    'Posp_Category': {type: String, default: ""},
    'Reporting_Agent_Name': {type: String, default: ""},
    'Reporting_Agent_Uid': Number,
    'Certification_Datetime': {type: Date},
    'Reporting_Email_ID': {type: String, default: ""},
    'Reporting_Mobile_Number': {type: String, default: ""},
    'FOS_Code': {Number},
    'ERPID_CreatedDate': {type: Date},
    'RegAmount': {type: Number, default: 0},
    'Channel': {type: String, default: ""},
    'Recruitment_Status': {type: String, default: ""},
    'Is_Contact_Sync': {type: String, default: ""},
    'Paid_On': {type: Date},
    'Cust_Id': {type: Number, default: 0},
    'IsFOS': {type: Boolean, default: false},
    'Is_Mail_Sent':{type:Number, default:2},
    'Name_On_PAN': {type: String, default: ""},
    'DOB_On_PAN': {type: String, default: ""},
    'Name_On_Aadhar': {type: String, default: ""},
    'Nominee_Name_On_Pan': {type: String, default: ""},
    'Nominee_DOB_On_Pan': {type: String, default: ""},
    "POSP_UploadedtoIIB": {type: String, default: ""},
    "POSP_DeActivatedtoIIB": {type: String, default: ""},
    "POSP_DeActivatedDateAtIIB": {type: Date},
    "POSP_Activated": {type: String, enum: ["Yes", "No"]},
    "POSP_ActivatedBy": {type: String},
    "POSP_ActivatedDate": {type: Date},
    "POSP_ActivatedReason": {type: String},
    "rzp_id": {type: String, default: ""},
    "POSP_DeActivatedBy": {type: Number},
    "POSP_DeActivatedReason": {type: String},
    'Verified_Mail_Sent':{type: String, default:"No"},
    'Approved_Mail_Sent':{type: String, default:"No"},    
    'Training_Scheduled_On': {type: Date},
    'Documents_Uploaded_On': {type: Date},
    'Documents_Rejected_On': {type: Date},
    'Documents_Rejected_By': {type: String},
    'Documents_Verified_On': {type: Date},
    'Documents_Approved_On': {type: Date},
    'Created_On': {type: Date},
    'Modified_On': {type: Date},
    "IIB_Modified_On" : {type: Date},
    "IIB_IP_Address" : {type: String, default: ""},
    "Digital_Signature_Status":{type: String, default: ""},
    "Digital_Signature_On":{type: Date},
	"Business_Profile":{type:Object}
});
posp_user_loginSchema.plugin(mongoosePaginate);
posp_user_loginSchema.plugin(autoIncrement.plugin, {model: 'posp_user', field: 'User_Id', startAt: 1});
let posp_user = connection.model('posp_user', posp_user_loginSchema);
module.exports = posp_user;

